version: '3.6'

services:
  agent:
    image: portainer/agent:latest
    build:
      context: ./portainer/
      dockerfile: Dockerfile.agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-net
    deploy:
      mode: global

  portainer:
    image: portainer/portainer:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - traefik-net
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.portainer.enable=true"
        - "traefik.backend=traefik"
        - "traefik.portainer.frontend.rule=Host:docker-admin.devinf"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.entrypoints=https,http"
#        - "traefik.http.redirect=https"
        - "traefik.port=9000"
        - "traefik.portainer.port=9000"

networks:
  traefik-net:
    external: true

volumes:
  portainer_data:
