version: "3.6"

services:
  traefik:
    image: traefik:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.traefik.enable=true"
        - "traefik.enable=true"
        - "traefik.backend=traefik"
        - "traefik.docker.network=traefik-net"
        - "traefik.traefik.frontend.rule=Host:dashboard.devinf"
#        - "traefik.frontend.entrypoints=https,http"
        - "traefik.port=8082"
        - "traefik.traefik.port=8082"
    volumes:
      - ./traefik-local.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock # Mount docker socket for connect to docker via socket.
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
